name: Build and deploy ASP.Net Core app to Azure Web App - app-CloudWorkshop

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_PATH: './src/Web'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build with dotnet
      run: dotnet build ${{ env.APP_PATH }} --configuration Release

    - name: dotnet publish
      run: dotnet publish ${{ env.APP_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-CloudWorkshop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37A56353DD7B4A189601B0D494BF2B71 }}
        package: ${{env.DOTNET_ROOT}}/myapp
